language: java
jdk:
- oraclejdk8
- openjdk8
- oraclejdk9
sudo: false
before_install:
- export MAVEN_OPTS="-Xms256m -Xmx1024m -Xss1024k" && path="$(pwd)" && cd .. && git clone --recursive https://github.com/kubernetes-client/java && cd java && git checkout client-java-parent-2.0.0 && mvn install -DskipTests && cd $path
script:
- mvn compile