language: java
jdk:
#- oraclejdk8 # Sometime it stalls while building Google Kubernetes API
#- openjdk8 # Causes too much StackOverflow error
- oraclejdk9
sudo: false
before_install:
- path="$(pwd)" && cd .. && git clone --recursive https://github.com/kubernetes-client/java && cd java && git checkout 8d6ab536f565ee951141b14bfd170629399d8c67 && MAVEN_OPTS="-Xms256m -Xmx1024m -Xss1024k" mvn -q install -DskipTests && cd $path
script:
- mvn javadoc:javadoc
