---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-creator-saccount
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-api-diagram
  namespace: kube-system
data:
  api-diagram.json: |
                   [
                     {
                       "name": "/vnf",
                       "path": [
                         {
                           "name": "/launch/:id",
                           "type": "post",
                           "function": "routes.vnf.LauncherRoute"
                         }
                       ]
                     }
                   ]
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: harbor-creator-deployment
  namespace: kube-system
  labels:
    k8s-app: harbor-creator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: harbor-creator
  template:
    metadata:
      labels:
        k8s-app: harbor-creator
        name: harbor-creator
    spec:
      containers:
        - name: harbor
          image: augugrumi/harbor:kubernetes_integration
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: harbor-config
              mountPath: /config
          env:
            - name: HARBOR_API_CONFIG
              value: /config/api-diagram.json
      volumes:
        - name: harbor-config
          configMap:
            name: harbor-api-diagram
---
kind: Service
apiVersion: v1
metadata:
  name: harbor-creator-service
  namespace: kube-system
spec:
  selector:
    k8s-app: harbor-creator
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: NodePort
